Concatenating all subjects data for stan

In [1]:
import numpy as np
import pandas as pd  
import glob
import os

In [2]:
os.getcwd()

'/Users/jackiebeltran/Documents/GitHub/RP_Learning/1_scripts/behavior'

In [3]:
flist = sorted(glob.glob('/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/*.csv'))
print('participants in this dataset are: ' + str(len(flist)))

participants in this dataset are: 75

In [4]:
flist

['/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/401.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/402.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/408.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/409.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/410.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/413.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/415.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/416.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/417.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/418.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/419.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/420.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/421.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/422.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/423.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/424.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/425.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/427.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/428.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/430.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/431.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/432.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/434.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/435.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/436.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/438.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/440.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/442.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/443.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/444.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/445.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/446.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/447.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/451.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/453.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/454.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/455.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/501.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/502.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/503.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/504.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/506.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/507.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/512.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/514.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/515.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/516.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/517.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/519.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/520.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/521.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/522.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/523.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/524.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/525.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/526.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/527.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/529.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/530.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/531.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/532.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/533.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/535.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/536.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/537.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/538.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/540.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/542.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/543.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/544.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/545.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/546.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/547.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/548.csv',
 '/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/N_75/549.csv']

In [5]:
# empty list to crreate a single dataframe with all subjects parameters
df1_dataframes = []

# load and append each df1 dataframe to the list
for file in flist:
    
    df = pd.read_csv(file)
    
    df1_dataframes.append(df)

combined_df = pd.concat(df1_dataframes, ignore_index=True)

In [6]:
combined_df

      Unnamed: 0  sub_ID  actions  rewards  condition
0              0     401        2       -1          2
1              1     401        1        0          1
2              2     401        1        0          3
3              3     401        1        0          2
4              4     401        1        1          1
...          ...     ...      ...      ...        ...
6745          85     549        1        1          1
6746          86     549        1        1          1
6747          87     549        1        0          3
6748          88     549        1        0          3
6749          89     549        1        0          1

[6750 rows x 5 columns]

In [7]:
def grouping(df):
    def categorize(sub_ID):
        if str(sub_ID).startswith('5'):
            return 'HC'
        elif str(sub_ID).startswith('4'):
            return 'MDD'
        else:
            return 'Other'

    df['group'] = df['sub_ID'].apply(categorize)
    return df

# Apply the function to the DataFrame
df = grouping(combined_df)

df = df.drop(['Unnamed: 0'], axis=1)

In [8]:
# save df as csv

df.to_csv('/Users/jackiebeltran/Documents/GitHub/RP_Learning/0_data/stan/data_N75.csv', index=False)

In [9]:
df

      sub_ID  actions  rewards  condition group
0        401        2       -1          2   MDD
1        401        1        0          1   MDD
2        401        1        0          3   MDD
3        401        1        0          2   MDD
4        401        1        1          1   MDD
...      ...      ...      ...        ...   ...
6745     549        1        1          1    HC
6746     549        1        1          1    HC
6747     549        1        0          3    HC
6748     549        1        0          3    HC
6749     549        1        0          1    HC

[6750 rows x 5 columns]